local utils = require("conf.utils.bindings")
local main_mod = utils.main_mod_bind
local mouse = utils.mouse_buttons

hl.define_submap("select_workspace", "reset", function()
  hl.bind("D", hl.dsp.focus({ workspace = "name:dashboard" }))
  hl.bind("W", hl.dsp.focus({ workspace = "name:web" }))
  hl.bind("C", hl.dsp.focus({ workspace = "name:code" }))
  hl.bind("M", hl.dsp.focus({ workspace = "name:music" }))
  hl.bind("T", hl.dsp.focus({ workspace = "name:messagers" }))
  hl.bind("S", hl.dsp.workspace.toggle_special("scratchpad"))
  hl.bind("escape", hl.dsp.submap("reset"))
  hl.bind("catchall", hl.dsp.submap("reset"))
end)

hl.define_submap("move_to_workspace", "reset", function()
  hl.bind("D", hl.dsp.window.move({ workspace = "name:dashboard" }))
  hl.bind("W", hl.dsp.window.move({ workspace = "name:web" }))
  hl.bind("C", hl.dsp.window.move({ workspace = "name:code" }))
  hl.bind("M", hl.dsp.window.move({ workspace = "name:music" }))
  hl.bind("T", hl.dsp.window.move({ workspace = "name:messagers" }))
  hl.bind("S", hl.dsp.window.move({ workspace = "special:scratchpad" }))
  hl.bind("escape", hl.dsp.submap("reset"))
  hl.bind("catchall", hl.dsp.submap("reset"))
end)

hl.bind("CTRL + F12", hl.dsp.workspace.toggle_special("terminal"))
hl.bind("SHIFT + F12", hl.dsp.workspace.toggle_special("notes"))
main_mod("K", hl.dsp.submap("select_workspace"))
main_mod("SHIFT + K", hl.dsp.submap("move_to_workspace"))
main_mod("left", hl.dsp.focus({ workspace = "e-1" }))
main_mod("right", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mouse.side_right, hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mouse.side_left, hl.dsp.focus({ workspace = "e-1" }))
