local utils = require("conf.utils.bindings")
local main_mod = utils.main_mod_bind
local mouse = utils.mouse_buttons

hl.define_submap("select_workspace", "reset", function()
  hl.bind("D", hl.dsp.focus({ workspace = "name:dashboard" }), { description = "Go to Dashboard WS" })
  hl.bind("W", hl.dsp.focus({ workspace = "name:web" }), { description = "Go to Web WS" })
  hl.bind("C", hl.dsp.focus({ workspace = "name:code" }), { description = "Go to Code WS" })
  hl.bind("M", hl.dsp.focus({ workspace = "name:music" }), { description = "Go to Music WS" })
  hl.bind("T", hl.dsp.focus({ workspace = "name:messagers" }), { description = "Go to Messagers WS" })
  hl.bind("S", hl.dsp.workspace.toggle_special("scratchpad"), { description = "Toggle special WS" })
  hl.bind("escape", hl.dsp.submap("reset"), { description = "Exit Submap" })
  hl.bind("catchall", hl.dsp.submap("reset"))
end)

hl.define_submap("move_to_workspace", "reset", function()
  hl.bind("D", hl.dsp.window.move({ workspace = "name:dashboard" }), { description = "Move window to Dashboard" })
  hl.bind("W", hl.dsp.window.move({ workspace = "name:web" }), { description = "Move window to Web" })
  hl.bind("C", hl.dsp.window.move({ workspace = "name:code" }), { description = "Move window to Code" })
  hl.bind("M", hl.dsp.window.move({ workspace = "name:music" }), { description = "Move window to Music" })
  hl.bind("T", hl.dsp.window.move({ workspace = "name:messagers" }), { description = "Move window to Messagers" })
  hl.bind("S", hl.dsp.window.move({ workspace = "special:scratchpad" }), { description = "Move window to special" })
  hl.bind("escape", hl.dsp.submap("reset"), { description = "Exit Submap" })
  hl.bind("catchall", hl.dsp.submap("reset"))
end)

hl.bind("CTRL + F12", hl.dsp.workspace.toggle_special("terminal"), { description = "Popup Terminal" })
hl.bind("SHIFT + F12", hl.dsp.workspace.toggle_special("notes"), { description = "Popup Notes" })
main_mod("K", hl.dsp.submap("select_workspace"), { description = "Workspaces Submap" })
main_mod("SHIFT + K", hl.dsp.submap("move_to_workspace"), { description = "Move to Workspace Submap" })
main_mod("left", hl.dsp.focus({ workspace = "e-1" }), { description = "Previous Workspace" })
main_mod("right", hl.dsp.focus({ workspace = "e+1" }), { description = "Next Workspace" })
hl.bind(mouse.side_right, hl.dsp.focus({ workspace = "e+1" }), { description = "Next Workspace" })
hl.bind(mouse.side_left, hl.dsp.focus({ workspace = "e-1" }), { description = "Previous Workspace" })
