hl.workspace_rule({ workspace = "1", persistent = true, default_name = "dashboard" })
hl.workspace_rule({ workspace = "2", persistent = true, default_name = "web" })
hl.workspace_rule({ workspace = "3", persistent = true, default_name = "code" })
hl.workspace_rule({ workspace = "4", persistent = true, default_name = "music" })
hl.workspace_rule({ workspace = "5", persistent = true, default_name = "messagers" })
