$mainMod = CTRL_ALT_SUPER # Sets main modifier

# App Launcher
bind = $mainMod, SPACE, execr, uwsm app -- vicinae toggle
bind = CONTROL, SPACE, execr, uwsm app -- $menu

# Main Global Bidings
bind = $mainMod, Return, exec, uwsm app -- $terminal
bind = SUPER, F5, exec, uwsm app -- ghostty -e nvim
bind = $mainMod, R, exec, uwsm app -- walker -s runner
bind = $mainMod, C, exec, uwsm app -- walker -s clipboard
bind = $mainMod, E, exec, uwsm app -- walker -s emojis
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exec, uwsm stop,
bind = $mainMod, F, exec, uwsm app -- $fileManager
bind = $mainMod, B, exec, uwsm app -- $browser
bind = CONTROL, F12, togglespecialworkspace, code
bind = SHIFT, F12, togglespecialworkspace, notes


# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Move focus with mainMod + arrow keys or cmd tab
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
bind = ALT, TAB, cyclenext
bind = ALT, TAB, exec, hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .specialWorkspace.name' | sed 's/special://' | xargs -I [] hyprctl dispatch togglespecialworkspace []
bind = ALT_SHIFT, TAB, cyclenext, prev

# HYPER + K -> Workspaces
bind = , mouse:275, workspace, e+1
bind = , mouse:276, workspace, e-1
bind = $mainMod, left, workspace, e-1
bind = $mainMod, right, workspace, e+1

bind = $mainMod, K, submap, workspace_select
submap=workspace_select

# Switch workspaces with mainMod + K, [D|W|C|M]
bind = , D, workspace, name:dashboard
bind = , D, submap, reset
bind = , W, workspace, name:web
bind = , W, submap, reset
bind = , C, workspace, name:code
bind = , C, submap, reset
bind = , M, workspace, name:music
bind = , M, submap, reset

bind = SHIFT, W, movetoworkspace, name:web
bind = SHIFT, W, submap, reset
bind = SHIFT, C, movetoworkspace, name:code
bind = SHIFT, C, submap, reset
bind = SHIFT, M, movetoworkspace, name:music
bind = SHIFT, M, submap, reset

bind = , S, togglespecialworkspace, magic
bind = , S, submap, reset
bind = SHIFT, S, movetoworkspace, special:magic
bind = SHIFT, S, submap, reset

bind = , catchall, submap, reset
submap = reset
# End Workspaces

bind = SUPER, TAB, exec, uwsm app -- walker -s windows
# HYPER + W -> Window Management
bind = $mainMod, W, submap, window_management
submap=window_management

bind = , SPACE, layoutmsg, focusmaster master
bind = , SPACE, submap, reset
bind = , N, layoutmsg, cyclenext
bind = , N, submap, reset
bind = , P, layoutmsg, cycleprev
bind = , P, submap, reset
bind = , F, togglefloating,
bind = , F, submap, reset
bind = , Return, layoutmsg, swapwithmaster auto
bind = , Return, submap, reset
bind = $mainMod, N, layoutmsg, swapnext
bind = $mainMod, N, submap, reset
bind = $mainMod, P, layoutmsg, swapprev
bind = $mainMod, P, submap, reset
bind = , catchall, submap, reset
submap = reset

# End Window Management

# HYPER + W -> Window Easy Motion
bind = $mainMod+SHIFT, W, submap, easy_motion

submap = easy_motion
bind = , F, easymotion, action:hyperctl dispatch focuswindow address:{}
bind = , C, easymotion, action:hyperctl dispatch closewindow address:{}
bind = , W, submap, workspace_motion

submap = workspace_motion
bind = SHIFT, W, easymotion, action:hyprctl dispatch movetoworkspace name:web, adress:{}
bind = SHIFT, W, submap, reset
bind = SHIFT, M, easymotion, action:hyprctl dispatch movetoworkspace name:music, adress:{}
bind = SHIFT, M, submap, reset
bind = SHIFT, D, easymotion, action:hyprctl dispatch movetoworkspace name:dashboard, adress:{}
bind = SHIFT, D, submap, reset
bind = , escape, submap, reset
bind = , catchall, submap, reset
submap = reset
# End Window Easy Motion
