$mainMod = SUPER # Sets "Windows" key as main modifier

# App Launcher
bind = SUPER, SPACE, execr, $menu
bind = SUPER+SHIFT, SPACE, execr, rofi -show run

# Main Global Bidings
bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, F, exec, $fileManager
bind = $mainMod, R, exec, $menu
bind = $mainMod, B, exec, $browser


# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Move focus with mainMod + arrow keys or cmd tab
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
bind = SUPER, TAB, cyclenext
bind = SUPER+SHIFT, TAB, cyclenext, prev

# HYPER + K -> Workspaces
bindm = $mainMod, mouse:275, workspace e+1
bindm = $mainMod, mouse:276, workspace e-1
bind = $mainMod, K, submap, workspace_select

submap=workspace_select

# Switch workspaces with altMod + [D|W|C|M]
bind = , D, workspace, name:dash
bind = , D, submap, reset
bind = , W, workspace, name:web
bind = , W, submap, reset
bind = , C, workspace, name:code
bind = , C, submap, reset
bind = , M, workspace, name:music
bind = , M, submap, reset

bind = SHIFT, W, movetoworkspace, name:web
bind = SHIFT, W, submap, reset
bind = SHIFT, C, movetoworkspace, name:code
bind = SHIFT, C, submap, reset
bind = SHIFT, M, movetoworkspace, name:music
bind = SHIFT, M, submap, reset

bind = , S, togglespecialworkspace, magic
bind = , S, submap, reset
bind = SHIFT, S, movetoworkspace, special:magic
bind = SHIFT, S, submap, reset

bind = , catchall, submap, reset
submap = reset
# End Workspaces

# HYPER + W -> Window Management
bind = $mainMod, W, submap, window_management

submap=window_management

bind = , SPACE, layoutmsg, focusmaster master
bind = , SPACE, submap, reset
bind = , N, layoutmsg, cyclenext
bind = , N, submap, reset
bind = , P, layoutmsg, cycleprev
bind = , P, submap, reset
bind = , F, togglefloating,
bind = , F, submap, reset
bind = , Return, layoutmsg, swapwithmaster auto
bind = , Return, submap, reset
bind = $mainMod, N, layoutmsg, swapnext
bind = $mainMod, N, submap, reset
bind = $mainMod, P, layoutmsg, swapprev
bind = $mainMod, P, submap, reset
bind = , catchall, submap, reset
submap = reset
# End Window Management

