env = MOZ_ENABLE_WAYLAND,1
env = HYPRCURSOR_SIZE,30
env = HYPRCURSOR_THEME,Gruv-Cursor
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = QT_QPA_PLATFORM,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = GDK_BACKEND,wayland
env = GTK_THEME,Gruvminimal
env = TERMINAL,ghostty
env = GTK_IM_MODULE,ibus
env = QT_IM_MODULE,ibus
