workspace = 1, persistent:true, defaultName:dashboard
workspace = 2, persistent:true, defaultName:web
workspace = 3, persistent:true, defaultName:music
workspace = special:code, on-created-empty:ghostty
workspace = special:notes, on-created-empty:logseq
