windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

windowrulev2 = float,class:^(nwg-look)$
windowrulev2 = float,class:^(pavucontrol)$

workspace = name:dash, monitor:HDMI-A-1, default:true, persistent: true
workspace = name:code, monitor:HDMI-A-1, persistent:true
workspace = name:music, monitor:HDMI-A-1, persistent:true
workspace = name:web, monitor:HDMI-A-1, persistent:true
