# exec-once = swaync # hyprpanel starts sway
exec-once = polkit-kde-agent
# exec-once = waybar
exec-once = hyprpanel
exec-once = systemctl --user start elephant.service
exec-once = systemctl --user start walker.service
exec-once = hyprpm reload -n
exec-once = ibus-daemon -drxR
